services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=todolist-db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
    ports:
      # Mapeia a porta 5432 DO CONTAINER para a porta 5432 DA SUA M√ÅQUINA
      - '5432:5432'
